from oops_proj import chatbook
user1=chatbook()
print(user1._chatbook__name) #Here we use __ before any variable inside class to protect it and so that we cannot access it from outside with using user1.__name.Bur to acces it from outside we have to write user1._classname__variablename.
print(user1.get_name())
user1.set_name("Soham")
print(user1.get_name())
user2=chatbook()
print(user2.id)
user3=chatbook()
print(user3.id)
user4=chatbook()
print(user4.id)
chatbook.set_id(10)
user5=chatbook()
print(user5.id)
